#!/bin/bash
# Reference: https://github.com/rossf7/label-schema-automated-build
docker build \
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
    --tag $IMAGE_NAME .
